### ISSUE TITLE
cargo can't download futures-util-preview 0.3.0-alpha.4

### ISSUE THREAD

**Issue by Arnavion** [rust-lang-nursery/futures-rs#1247]
Cargo.toml contains

```toml
[dependencies]
futures-util-preview = { version = "0.3.0-alpha.4", features = ["compat"] }
```

`cargo update` fails with:

```
error: no matching version `^0.3.0-alpha.4` found for package `futures-util-preview`
location searched: registry `https://github.com/rust-lang/crates.io-index`
versions found: 0.2.2
```

With `RUST_LOG=debug` :

```
INFO 2018-09-02T20:33:03Z: cargo::sources::registry::index: failed to parse `futures-util-preview` registry package: Feature `compat` includes `futures01` which is neither a dependency nor another feature
```

This is with latest nightly cargo `cargo 1.29.0-nightly (0ec7281b9 2018-08-20)`. Seems it doesn't like the crate renaming feature.
