### ISSUE TITLE
Circular dependency with rand

### ISSUE THREAD

**Issue by Pauan** [rust-lang-nursery/futures-rs#1489]
Here is a reduced test case:

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = { version = "0.4.10", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
rand = { version = "0.6.5", features = ["stdweb"] }
```

When I run `cargo build` I get this error:

```
error: cyclic package dependency: package `rand v0.6.5` depends on itself. Cycle:
package `rand v0.6.5`
    ... which is depended on by `futures-util-preview v0.3.0-alpha.13`
    ... which is depended on by `stdweb v0.4.15`
    ... which is depended on by `rand_os v0.1.3`
```

After scratching my head at this for quite a while, I figured it out:

* The `rand` crate has optional support for generating random numbers on wasm32 (that's what the `stdweb` feature enables).

* The `stdweb` crate has optional support for using JS Promises as Futures (that's what the `experimental_features_which_may_break_on_minor_version_bumps` feature enables).

* The `futures_util` crate has *non-optional* support for using `rand` (this is used for the `select` macro).

This then creates a cycle: `futures_util` needs `rand`, which needs `stdweb`, which needs `futures_util`.

I don't have any great solutions for this. Removing `rand` from the `std` feature will fix the immediate problem, but then what if somebody *wants* to use the `select` macro...?

**Comment by Pauan** [comment]
I still get circular dependency errors even when I nuke all the features:

```toml
[dependencies.futures-util-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-executor-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-test-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-core-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-channel-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-io-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-sink-preview]
version = "0.3.0-alpha.13"
default-features = false

[dependencies.futures-preview]
version = "0.3.0-alpha.13"
default-features = false
```

I'm surprised, I was expecting that using `default-features = false` would have fixed it.
