### ISSUE TITLE
futures-preview-0.3.0-alpha.13 build fails on nightly-2019-04-08 or later

### ISSUE THREAD

**Issue by taiki-e** [rust-lang-nursery/futures-rs#1518]
Probably it will take a while to release the next version.

It can be avoided by pinning the nightly toolchain to the 2019-04-07 or early.

**Comment by Nemo157** [comment]
Now that #1514 has been merged `master` once again works on the latest nightly (for now...). If you want to prepare for the new release (or have other reasons you can't stay on `nightly-2019-04-07` or earlier) you can override the crate in your `Cargo.toml`:

```toml
[patch.crates-io]
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-core-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-util-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-sink-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-channel-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-executor-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-io-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-test-preview = { git = "https://github.com/rust-lang-nursery/futures-rs" }
```

this will apply throughout your dependency tree, so will likely fail if you have dependencies that directly implement the `Future` trait unless they also prepare for the next version, but ¯\\\_(ツ)\_/¯ such is life on nightly (and thank you to everyone that is willing to help test this stuff while it's on nightly).
